// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"N_SaveManager","status":true,"description":"v1.00 Save files asynchronously and use deflate compression.","parameters":{}},
{"name":"N_BloatSave","status":true,"description":"N1.00 Adds data to bloat the save file.","parameters":{}}
];
